<a href="https://colab.research.google.com/github/tazeem1920/pytorch_tutorial/blob/main/Deep_learning_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

We gonna learn pytorch. TF is old and gone now.

In [17]:
# first thing first
import torch

Tensors

Array= simple data type
list= multi dimentional multiple data types
Tensor= multi dimentional matrix of single data type (advanced version of list) works much better with GPUs.

In [1]:
import numpy as np

LIST

In [3]:
my_list=[[1,2,3,4,5],[7,8,9,10]]

Numpy array

In [15]:
np1=np.random.rand(3,4)
np1

array([[0.72549112, 0.70145874, 0.99429214, 0.22412817],
       [0.11363377, 0.65467648, 0.08593923, 0.24210443],
       [0.3068959 , 0.12477989, 0.7301957 , 0.54717872]])

Tensor

In [18]:
tensor_2d=torch.randn(3,4)
tensor_2d

tensor([[-0.1305, -1.3790, -0.8990, -0.5513],
        [ 1.4877, -1.2184, -0.4075,  0.8006],
        [-2.1276, -0.5364,  0.5034,  0.8260]])

In [23]:
tensor_3d=torch.randn(2,3,4)
tensor_3d

tensor([[[ 0.5562,  1.2894,  0.5907,  0.8898],
         [-0.0556, -0.5103,  0.2641,  0.3946],
         [-0.2235,  0.7000, -0.4022,  2.2191]],

        [[ 1.7567, -0.9585, -1.0898,  0.2255],
         [-0.4440, -1.2145,  1.4220,  0.9564],
         [-0.9661,  0.6794, -0.1406, -0.4551]]])

In [27]:
tensor_3d_zero=torch.zeros(2,3)
tensor_3d_zero

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [28]:
tensor_3d_zero.dtype

torch.float32

In [29]:
#we can  also create tensor from numpy array.

In [31]:
converted_tensor=torch.tensor(np1)
converted_tensor

tensor([[0.7255, 0.7015, 0.9943, 0.2241],
        [0.1136, 0.6547, 0.0859, 0.2421],
        [0.3069, 0.1248, 0.7302, 0.5472]], dtype=torch.float64)